# Generated by Django 5.2.3 on 2025-06-26 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('work_hours', models.IntegerField()),
                ('time_management', models.IntegerField()),
                ('distraction_level', models.CharField(max_length=10)),
                ('task_satisfaction', models.IntegerField()),
                ('meeting_effectiveness', models.IntegerField()),
                ('energy_preference', models.CharField(max_length=10)),
                ('stress_level', models.IntegerField()),
                ('work_life_balance', models.IntegerField()),
                ('career_satisfaction', models.IntegerField()),
                ('learning_motivation', models.IntegerField()),
                ('biggest_challenge', models.TextField()),
                ('growth_area', models.CharField(max_length=50)),
                ('team_collaboration', models.IntegerField()),
                ('communication_style', models.CharField(max_length=20)),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('ai_recommendations', models.TextField(blank=True, null=True)),
                ('wellness_score', models.CharField(blank=True, max_length=100, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment_app.employee')),
            ],
        ),
    ]
