# Generated by Django 5.2.3 on 2025-06-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='wellness_score',
            field=models.CharField(blank=True, null=True),
        ),
    ]
